### ISSUE TITLE
Circumstances

### ISSUE THREAD

**Issue by CharaArc** [bguns/KingmakerMods#1]
>*Special note regarding the Outflank feat and the Mad Dog's Pack Tactics feature: these feats both state that they increase the bonus from flanking to +4, but the game implemented this as a simple +2 Circumstantial bonus. This meant that in certain (admittedly rare) circumstances, these bonuses could stack to a total of +6 from flanking. This has been fixed, these features now increase the actual flanking bonus to (maximum) +4

Circumstance bonuses always stack from different sources.

**Comment by bguns** [comment]
The problem is not whether or not the Circumstance bonus should stack or not, the problem is that it should not be a Circumstance bonus in the first place. Or any kind of extra bonus for that matter. These features increase the Flanking bonus from +2 to +4. Nothing more.
